language: node_js
node_js: 8.11.1
script:
  - npm install
  - npm run build
  - git describe
deploy:
  provider: releases
  api_key:
    secure: 6d3xrjPgKC5hGq1ds2wvmWWmg+VoPdOcFRZy11ToEom36YMRIClenqcywJi4O7DgF4bJLTRMNjCsppQAupTybFQiiWu/SITHerJbeoH1My3zHZFb8KoglQNPdmpT/Mo7aAWwxeo+4rUw5ehOeGdUVMxneh1E4XCBYMcHWoGQlPLsLLaVN50vCWZB9aCDeQbfHMF/FZ0SuHpsWC1JB7GlwO64x0wMsoFkNfi9+Kd1tpS5rjiVuX4pqB7lDkGeujaBxfozPK+TGn3b+PK/asqFUltpw4VQY9gUxySzSiWK4GsjopoTHdlrCQ32kq47hKESpLKWuDrI+uN6aqK9cuWlPGEbTIcn1C5XtGiOVF76PUXStmoMYUnoZzfX9kzcXY0CBLZ55L5BJieykzSJhmjYIDiWL0+rBpLgc6tuUjoXsvm4NxWHhoyrCwSQ77I57Xrzr0P2BIFM3gN55qyLU8I/8TcQ7hLCfZ5HHnqt8YDFY3xHxPKJKyDe9u+4PdfTc2i+GUDp+KuXTyX/ZhNaiRTfff231pR+8Y+dUPQIUSzVkoLezV3zCxCStKgkCyDED1hAK4ZTf4CTERCrFfTJP9bg6aVCuRO/XzeP9NyYDzlBJQyChvJUh3kDNlh7cEfXqLFznxaQBwlTmsFXixNdXYh04i+9IOW16EwlJHTpUocPBDg=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    repo: fortinet/fortigate-autoscale-aws-tgw
    tags: true
    branch: master
